title: FGU Technologies
author: Jack Hudson
description: >-
  Empowering Freedom Go Up
baseurl: "/"
url: "https://www.fgutechnologies.com/"
icon: /assets/images/favicon.png
twitter_username: fgutechnologies
github_username: fgutechnologies

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
